AWSTemplateFormationVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda local demo

Resources:
  BeerAvailableFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: BeerInventory/
      Handler: IsBeerAvailable.handler
      Runtime: python3.7
#      Events:
#        ApiEvents:
#          Type: Api
#          Properties:
#            Path: /isbeeravailable
#            Method: GET