AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: brewery-application

Globals:
  Api:
    OpenApiVersion: '3.0.1'
    TracingEnabled: true

Resources:
  BrewOrderService4SaveBrewOrder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: BrewOrder/SaveBrewOrder/SaveBrewOrder.zip
      Handler: SaveBrewOrder.handler
      Runtime: python3.6
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /breworders
            Method: POST